name: Docker website CI

on:
  push:
    branches: ["master"]
    paths:
      - 'src/**'

jobs:
  deploy:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub  # Corregido el nombre
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build website image
        run: |
          docker build --platform linux --tag mvrcentes/condoadminfront:latest --no-cache -f Dockerfile .
      - name: Publish website image
        run: |
          docker push mvrcentes/condoadminfront:latest
      - name: App service auth
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'condoadminfront'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'mvrcentes/condoadminfront:latest'
